import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  content: ["./src/app/**/*.{ts,tsx}", "./src/components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#425646",
        secondary: "#924a31",
        tertiary: "#6f4a00",
        background: "#fbf9f4",
        surface: "#fbf9f4",
        "surface-bright": "#fbf9f4",
        "surface-dim": "#dbdad5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container": "#f0eee9",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "surface-variant": "#e4e2dd",
        "surface-tint": "#4f6353",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#434843",
        "on-background": "#1b1c19",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#0d1f12",
        "on-primary-fixed-variant": "#384b3c",
        "on-secondary-fixed": "#390c00",
        "on-secondary-fixed-variant": "#75331c",
        "on-secondary-container": "#78361e",
        "on-tertiary-fixed": "#291800",
        "on-tertiary-fixed-variant": "#614000",
        "on-tertiary-container": "#ffe6c6",
        "primary-fixed": "#d2e8d3",
        "primary-fixed-dim": "#b6ccb8",
        "primary-container": "#5a6e5d",
        "on-primary-container": "#d9f0da",
        "secondary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#ffb59d",
        "secondary-container": "#fea182",
        "tertiary-fixed": "#ffddb0",
        "tertiary-fixed-dim": "#fabb57",
        "tertiary-container": "#8e6000",
        "inverse-primary": "#b6ccb8",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f1ec",
        outline: "#737872",
        "outline-variant": "#c3c8c1",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        unit: "8px",
        "section-gap": "120px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg": ["\"Playfair Display\"", "serif"],
        "headline-lg": ["\"Playfair Display\"", "serif"],
        "headline-lg-mobile": ["\"Playfair Display\"", "serif"],
        "headline-md": ["\"Playfair Display\"", "serif"],
        "headline-sm": ["\"Playfair Display\"", "serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile": [
          "36px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [forms],
};

export default config;
